services:
  postgres:
    image: postgis/postgis:15-master
    container_name: postgres
    environment:
      POSTGRES_USER: lolfucjj
      POSTGRES_PASSWORD: lolfucjj
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  accounts_service:
    build:
      context: ..
      dockerfile: cmd/accounts_service/Dockerfile
    container_name: accounts_service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
      
  posts_service:
    build:
      context: ..
      dockerfile: cmd/posts_service/Dockerfile
    container_name: posts_service
    depends_on:
      - postgres
    ports:
      - "8082:8082"

  api_service:
    build:
      context: ..
      dockerfile: cmd/api_service/Dockerfile
    container_name: api_service
    depends_on:
      - postgres
      - accounts_service
      - posts_service
    ports:
      - "8083:8083"